### ISSUE TITLE
Version 7.2 Splash: True

### ISSUE THREAD

**Issue by ctaity** [flowplayer/flowplayer#1273]
With splash true, we need touch 2 twice play. FIrst go away splash, second video play.

**Comment by nnarhinen** [comment]
Which browser? Example URL too please.

**Comment by ctaity** [comment]
Ok i will do a example

**Comment by denizb** [comment]
I am having the same issue. Chrome Version 62.0.3202.62 (Official Build) (64-bit) and Safari 11 on Mac OS High Sierra 10.13. 

The issue started right after upgrading from 7.04 to 7.2. Could be related to HLS playback. I am using the hlsjs.light extension.

Console log shows the following errors.

Uncaught TypeError: Cannot read property 'end' of undefined
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: n.forEach is not a function
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: Cannot read property 'end' of undefined
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: n.forEach is not a function
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: Cannot read property 'end' of undefined
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: n.forEach is not a function
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: Cannot read property 'end' of undefined
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: n.forEach is not a function
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: Cannot read property 'end' of undefined
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9
flowplayer.min.js:8 Uncaught TypeError: n.forEach is not a function
    at flowplayer.min.js:8
    at HTMLDivElement.s (flowplayer.min.js:7)
    at Object.e.trigger (flowplayer.min.js:7)
    at HTMLVideoElement.<anonymous> (flowplayer.hlsjs.light.min.js:23)
    at i (flowplayer.min.js:9)
    at HTMLVideoElement.a (flowplayer.min.js:9)
    at HTMLVideoElement.j (flowplayer.min.js:9)
(anonymous) @ flowplayer.min.js:8
s @ flowplayer.min.js:7
e.trigger @ flowplayer.min.js:7
(anonymous) @ flowplayer.hlsjs.light.min.js:23
i @ flowplayer.min.js:9
a @ flowplayer.min.js:9
j @ flowplayer.min.js:9

**Comment by nnarhinen** [comment]
This has to be fixed in the hlsjs engine
